version: "3.0"

services:
  hlds:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/cstrk52:/server/hlds_l/cstrk52 
      - ./config/cstrk61:/server/hlds_l/cstrk61
      - ./config/cstrk40:/server/hlds_l/cstrk40 

    ports:
      - 27015:27015
      - 27015:27015/udp
    command:
      - ./hlds_run -port 27015 -game cstrk61 +map de_dust +maxplayers 16
