version: "3.5"

services:
  hlds:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000" # <- Change this to your UID:GID
    volumes:
      - ./config/cstrk52:/server/hlds_l/cstrk52 
      - ./config/cstrk61:/server/hlds_l/cstrk61
      - ./config/cstrk40:/server/hlds_l/cstrk40 
      - ./config/cstrk31:/server/hlds_l/cstrk31 
    ports:
      - 27015:27015
      - 27015:27015/udp
    command:
      - -port 27015 -game cstrk61 +map de_dust +maxplayers 16
    security_opt:
      - no-new-privileges:1